# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

SUBDIRS += osgQT \
           gui \
           command \
           tools \
           simulation \
           simulator \
           editor 
TEMPLATE = subdirs 
CONFIG += release \
          warn_on \
          qt \
          thread 
OBJECTS_DIR = ./objects 
UI_DIR = ./ui 
MOC_DIR = ./moc 
