# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./osgQT
# Target is a library:  

SOURCES += qteventadapter.cpp \
           qtviewer.cpp 
HEADERS += qtactionadapter.h \
           qteventadapter.h \
           qtviewer.h 
TEMPLATE = lib 
CONFIG += release \
          warn_on \
          qt \
          staticlib 
QMAKE_CXXFLAGS_RELEASE += -O3 
OBJECTS_DIR = ../objects 
UI_DIR = ../ui 
MOC_DIR = ../moc 
